language: python

branches:
  only:
  - master

before_install:
  - sudo apt-get install graphviz
  - mkdir output

script:
  - neato -Tpng -Gdpi=300 dependencies.dot -o output/dependencies.png

deploy:
  provider: pages
  local-dir: output
  target-branch: artifacts
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
