theme: jekyll-theme-cayman
title: Ansible roles
description: Written in a <a href="style.html">simple style</a>, work on many distributions and <a href="https://www.ansible.com/">Ansible</a> versions.
